title: "Chaohui Feng - Academic Homepage"
name: "Chaohui Feng"
email: "cfeng224@uwo.ca"
description: "Earthquake-Tsunami Laboratory"

markdown: kramdown
permalink: /:title/

plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
