# 最简化配置
title: "Chaohui Feng - Academic Homepage"
name: "Chaohui Feng"
email: "fengchaohui23@mails.ucas.ac.cn"
description: "Earthquake Simulation & Cascading Geo-Hazards Researcher"

# 基本设置
markdown: kramdown
permalink: /:title/

# 不添加任何插件
plugins: []

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md